#!/bin/bash

docker build --build-arg PHP_VERSION=7.4 -t vavyskov/php:7.4-apache-buster .
docker push vavyskov/php:7.4-apache-buster

docker build --build-arg PHP_VERSION=7.3 -t vavyskov/php:7.3-apache-buster .
docker push vavyskov/php:7.3-apache-buster
