#!/bin/bash

docker build --build-arg PHP_VERSION=7.4 -t vavyskov/php:7.4-fpm-alpine3.11 .
docker push vavyskov/php:7.4-fpm-alpine3.11

docker build --build-arg PHP_VERSION=7.3 -t vavyskov/php:7.3-fpm-alpine3.11 .
docker push vavyskov/php:7.3-fpm-alpine3.11
