#!/bin/bash

#docker build --build-arg PHP_VERSION=7.4 -t vavyskov/php:7.4-fpm-ssh-alpine3.11 .
docker build --build-arg PHP_VERSION=7.4 -t vavyskov/php:7.4-fpm-ssh-alpine3.11:${DOCKER_TAG//,/ -t vavyskov/php:7.4-fpm-ssh-alpine3.11:} .
docker push vavyskov/php:7.4-fpm-ssh-alpine3.11

#docker build --build-arg PHP_VERSION=7.3 -t vavyskov/php:7.3-fpm-ssh-alpine3.11 .
#docker push vavyskov/php:7.3-fpm-ssh-alpine3.11
